name: my_health
description: Discovery Flutter Challenge App

# Remove this line if you wish to publish to pub.dev
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  http: ^0.13.5
  http_interceptor: ^1.0.2
  json_annotation: ^4.6.0
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  global_configuration: ^2.0.0-nullsafety.1
  image_picker: ^0.8.5+3
  google_mlkit_text_recognition: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  json_serializable: ^6.1.5
  injectable_generator: ^1.5.3

  # The lint set provided by the package is activated in the
  # `analysis_options.yaml` file located at the root of your package.
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # Config
    - assets/config/appsettings.json
    - assets/config/secrets.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware